---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-game-cron-job
  namespace: ng-game-cron-job
  labels:
    app: ng-game-cron-job
    namespace: ng-game-cron-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ng-game-cron-job
      namespace: ng-game-cron-job
  template:
    metadata:
      labels:
        app: ng-game-cron-job
        namespace: ng-game-cron-job
    spec:
      containers: #container is array. - is element of array
        - name: ng-game-cron-job
          image: 737121988715.dkr.ecr.us-west-2.amazonaws.com/ng/ng-game-cron-job:v1
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: '0.1'
              memory: 0.5Gi
          livenessProbe:
            httpGet:
              path: /CheckTesting
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /CheckTesting
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - ng-game-cron-job
                topologyKey: "kubernetes.io/hostname"

---
apiVersion: v1
kind: Service
metadata:
  name: ng-game-cron-job
  namespace: ng-game-cron-job
spec:
  selector:
    app: ng-game-cron-job
    namespace: ng-game-cron-job
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ng-game-cron-job
  namespace: ng-game-cron-job
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ng-game-cron-job1.profoundly.me
      http:
        paths:
          - path: /
            backend:
              serviceName: ng-game-cron-job
              servicePort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ng-game-cron-job
  namespace: ng-game-cron-job
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ng-game-cron-job
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
